name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest takes forever to run
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js from volta
      uses: volta-cli/action@v1
    - run: npm ci
    - run: npm run test:ci
    - run: npm run test:ci-safari
      if: ${{ matrix.os == 'macos-latest' }}
